// !!! This is a file automatically generated by hipify!!!
#pragma once
// Redirect: hipify-gen'd duplicate of c10/hip/HIPException.h (same CUDA-named
// content). Pull the cuda twin so CUDAError / C10_CUDA_CHECK are defined once.
#include <c10\hip\HIPException_hip.h>
