// !!! This is a file automatically generated by hipify!!!
#pragma once
// Redirect: hipify-gen'd duplicate of c10/hip/HIPFunctions.h (default-argument
// redefinition when both twins load). Pull the cuda twin so current_device and
// friends are declared exactly once.
#include <c10\hip\HIPFunctions_hip.h>
