// !!! This is a file automatically generated by hipify!!!
#pragma once
// Redirect: hipify-gen'd duplicate of c10/hip/HIPStream.h (redefines the
// CUDAStream class / stream priorities / default args). Pull the cuda twin,
// which the force-include shim already loads.
#include <c10\hip\HIPStream_hip.h>
